name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: sast-scan
        uses: AppThreat/sast-scan-action@1.0.2
        with:
          type: python
      - name: secret-scan
        uses: zricethezav/gitleaks-action@v1.5.0
      - name: dependency-scan
        uses: aufdenpunkt/python-safety-check@v1.0.4
  
  secrets-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: run secrets scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

  sast-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run sast scan
        uses: AppThreat/sast-scan-action@master
        with:
          output: reports
          type: python

  dependency-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run dependency scan
        uses: actions/dependency-review-action@v3
        with:
          fail-on-severity: high
